"""Add role column to users table

Revision ID: 5ea0f857da65
Revises: 
Create Date: 2025-09-29 20:31:46.971869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea0f857da65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'sheep_gender',
               existing_type=sa.TEXT(),
               type_=sa.Enum('EWE', 'RAM', name='sheepgender'),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('customer', 'user', 'admin', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'user', 'admin', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'"))
    op.alter_column('animals', 'sheep_gender',
               existing_type=sa.Enum('EWE', 'RAM', name='sheepgender'),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
