"""add_sellable_fields_to_animals

Revision ID: b47e4346b20c
Revises: 001_initial_role
Create Date: 2025-10-02 16:34:00.894979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47e4346b20c'
down_revision: Union[str, None] = '001_initial_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    allowed_shares_enum = sa.Enum('HALF', 'WHOLE', name='allowedshares', create_type=True)
    allowed_shares_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('animals', sa.Column('is_sellable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('animals', sa.Column('allowed_shares', sa.Enum('HALF', 'WHOLE', name='allowedshares', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'allowed_shares')
    op.drop_column('animals', 'is_sellable')

    # Drop the enum type
    sa.Enum(name='allowedshares').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
